### PR TITLE
s390x support

### PR DESCRIPTION
**Pull request by dmittelstaedt**
Adds s390x support, creating binary running on IBM Z.

### CODE REVIEW

**Comment by dmittelstaedt** [comment]
@mcred You need the specific hardware (IBM Z oder IBM Linux one) to finally test this build. I tested the build at work. Here is the output. Do you need an error-free output? I could provide it the next week with a liquibase installation.

root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# pwd
/go/src/github.com/liquibase/liquibase-package-manager
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# make s390x
GOOS=linux GOARCH=s390x go build -o /go/src/github.com/liquibase/liquibase-package-manager/bin/s390x/lpm /go/src/github.com/liquibase/liquibase-package-manager/cmd/lpm/darwin.go
cd /go/src/github.com/liquibase/liquibase-package-manager/bin/s390x && zip lpm-`cat /go/src/github.com/liquibase/liquibase-package-manager/VERSION`-s390x.zip lpm
updating: lpm (deflated 51%)
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# file bin/s390x/lpm
bin/s390x/lpm: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, Go BuildID=BnODOFPnYsLlfv8FE-q-/7d-f8Acvd8hW6AUGy71N/dzOX1rry8-IlyWgbxVvx/iHlfmsYl4gSaaKjS7-EF, not stripped
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# export PATH=${PATH}:bin/s390x
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# make test-setup
curl -Ls https://github.com/mcred/vexrun/releases/download/v0.0.5/vexrun-0.0.5.jar -z /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -o /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# make e2e
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/version.yml -p VERSION `cat /go/src/github.com/liquibase/liquibase-package-manager/VERSION`
can get proper version from lpm: FAILED
Result(exitValue=1, stdout=Unable to locate Liquibase., stderr=)
make: *** [Makefile:51: test-version] Error 1
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# uname -a
Linux 223e5b65c7d1 4.18.0-348.20.1.el8_5.s390x #1 SMP Tue Mar 8 13:01:59 EST 2022 s390x GNU/Linux
root@223e5b65c7d1:/go/src/github.com/liquibase/liquibase-package-manager# lpm
Unable to locate Liquibase.

**Comment by mcred** [comment]
You should be able to get past this with an environment variable pointing to a pseudo liquibase_home. The E2E tests only test the LPM methods and don't actually call liquibase. 

https://github.com/liquibase/liquibase-package-manager#setup

The following should get you past this error:
```
export LIQUIBASE_HOME=/usr/local/opt/liquibase/libexec
```

**Comment by dmittelstaedt** [comment]
Setting the environment variable works. Thank you. And the test passed.

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# uname -a
Linux b9d8ee8b9608 4.18.0-348.20.1.el8_5.s390x #1 SMP Tue Mar 8 13:01:59 EST 2022 s390x GNU/Linux
```

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# file bin/s390x/lpm
bin/s390x/lpm: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, Go BuildID=BnODOFPnYsLlfv8FE-q-/7d-f8Acvd8hW6AUGy71N/dzOX1rry8-IlyWgbxVvx/iHlfmsYl4gSaaKjS7-EF, not stripped
```

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# make test-setup
curl -Ls https://github.com/mcred/vexrun/releases/download/v0.0.5/vexrun-0.0.5.jar -z /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -o /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar
```

`root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# export LIQUIBASE_HOME=/usr/local/opt/liquibase/libexec`

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# make e2e
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/version.yml -p VERSION `cat /go/src/github.com/liquibase/liquibase-package-manager/VERSION`
can get proper version from lpm: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/add.yml
can add one package: PASSED
verify one package: PASSED
can add multi packages: PASSED
verify multi packages: PASSED
can add specific version: PASSED
verify specific version: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/completion.yml
can generate bash completion: PASSED
can generate zfs completion: PASSED
can generate fish completion: PASSED
can generate powershell completion: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/help.yml
can get help output: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/install.yml
can remove installed packages: PASSED
can install packages from liquibase.json: PASSED
verify installed packages: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/list.yml
can list installed packages: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/remove.yml
can remove one package: PASSED
verify one package removed: PASSED
can remove multi packages: PASSED
verify multi packages removed: PASSED
java -jar /go/src/github.com/liquibase/liquibase-package-manager/utils/vexrun.jar -f /go/src/github.com/liquibase/liquibase-package-manager/tests/endtoend/search.yml
can search all: PASSED
can search drivers: PASSED
can search extensions: PASSED
can search by term: PASSED
rm -Rf /go/src/github.com/liquibase/liquibase-package-manager/liquibase_libs
rm /go/src/github.com/liquibase/liquibase-package-manager/liquibase.json
```

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# echo $?
0
```

```
root@b9d8ee8b9608:/go/src/github.com/liquibase/liquibase-package-manager# lpm
Easily manage external dependencies for Database Development.
Search for, install, and uninstall liquibase drivers, extensions, and utilities.

Usage:
  lpm [command]

Available Commands:
  add         Add Packages
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  install     Install Packages from liquibase.json
  list        List Installed Packages
  remove      Removes Package
  search      Search for Packages
  update      Updates the Package Manifest

Flags:
      --category string   extension, driver, or utility
  -h, --help              help for lpm
  -v, --version           version for lpm

Use "lpm [command] --help" for more information about a command.
```

**Comment by mcred** [comment]
Thanks so much @dmittelstaedt! I updated the release for v0.1.5 to include the s390x binary. I would also like to connect and learn more about your usage of lpm when it's convenient for you. 

https://github.com/liquibase/liquibase-package-manager/releases/tag/v0.1.5

**Pull request merged**
